### ISSUE TITLE
Error inlining external image asset

### ISSUE THREAD

**Issue by edwardhorsford** [popeindustries/inline-source#77]
Should this work to inline external image assets? Skimming the docs and past issues I think it should.

My markup:
```html
<img class="" src="https://res.cloudinary.com/djmfyuq58/image/upload/c_limit,w_100,q_20,e_blur:300/v1536790539/ENMH_D800_27279.jpg" data-src="" data-ext="jpg" alt="" inline>
```

The error I get:
```
essage:
    ENOENT: no such file or directory, open '[LOCAL PATH REMOVED]http:/res.cloudinary.com/djmfyuq58/image/upload/c_limit,w_100,q_20,e_blur:300/v1536790539/ENMH_D800_27279.jpg'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: [LOCAL PATH REMOVED]http:/res.cloudinary.com/djmfyuq58/image/upload/c_limit,w_100,q_20,e_blur:300/v1536790539/ENMH_D800_27279.jpg
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
